name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/upload-artifact@3c86efb3ebea0d14eaf564c4dc5d5db17655c4ed
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Upload release APK
        uses: actions/upload-artifact@v3
        with:
        name: PackageBuddy-Release-APK
        path: app/build/outputs/apk/release/*.apk
